export { client } from "@/lib/content/client";
export { type ContentLanguage as ContentLanguageEntry } from "@/lib/content/client/content/languages";
export { type ContentLicense as ContentLicenseEntry } from "@/lib/content/client/content/licenses";
export { type ContentType as ContentTypeEntry } from "@/lib/content/client/content/types";
export { type Curriculum } from "@/lib/content/client/curricula";
export { type Documentation } from "@/lib/content/client/documentation";
export { type IndexPage } from "@/lib/content/client/index-page";
export { type LegalNotice } from "@/lib/content/client/legal-notice";
export { type Navigation } from "@/lib/content/client/navigation";
export { type Person } from "@/lib/content/client/people";
export { type Resource } from "@/lib/content/client/resources";
export { type EventResource } from "@/lib/content/client/resources/events";
export { type ExternalResource } from "@/lib/content/client/resources/external";
export { type HostedResource } from "@/lib/content/client/resources/hosted";
export { type PathfinderResource } from "@/lib/content/client/resources/pathfinders";
export { type Source } from "@/lib/content/client/sources";
export { type Tag } from "@/lib/content/client/tags";
export { config } from "@/lib/content/config";
export { config as keystaticConfig } from "@/lib/content/keystatic/config";
export { rewriteUrl } from "@/lib/content/keystatic/utils/rewrite-url";
export * from "@/lib/content/options";
export { resources as sharedMetadata } from "@/lib/content/shared-metadata.config";
export { createResourceMetadata } from "@/lib/content/utils/create-resource-metadata";
export { getLinkProps, type LinkSchema } from "@/lib/content/utils/get-link-props";
