allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  sharp: true
  simple-git-hooks: true
  typesense-instantsearch-adapter: true
  unrs-resolver: true

patchedDependencies:
  "@keystatic/core": patches/@keystatic__core.patch
  next: patches/next.patch

shellEmulator: true
