onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - node
  - sharp
  - simple-git-hooks
  - typesense-instantsearch-adapter
  - unrs-resolver
  - vue-demi

patchedDependencies:
  '@keystar/ui': patches/@keystar__ui.patch
  '@keystatic/core@0.5.48': patches/@keystatic__core@0.5.48.patch
  next: patches/next.patch

shellEmulator: true

strictDepBuilds: true
