onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - esbuild
  - node
  - sharp
  - simple-git-hooks
  - typesense-instantsearch-adapter
  - unrs-resolver
  - vue-demi

patchedDependencies:
  next: patches/next.patch

# https://pnpm.io/settings#shellemulator
shellEmulator: true

# https://pnpm.io/settings#strictdepbuilds
strictDepBuilds: true
