onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - node
  - sharp
  - simple-git-hooks
  - typesense-instantsearch-adapter
  - unrs-resolver

patchedDependencies:
  mermaid-isomorphic: patches/mermaid-isomorphic.patch
  next: patches/next.patch
