allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  lefthook: true
  sharp: true

engineStrict: true

minimumReleaseAge: 1440

patchedDependencies:
  "@keystatic/core": patches/@keystatic__core.patch
  next: patches/next.patch

shellEmulator: true
