name: Propose a resource
description: Provide metadata for a resource to be included in DARIAH-Campus
assignees:
  - ttasovac
  - vickygarnett
labels:
  - new resource
type: content
body:
  - type: markdown
    attributes:
      value:
        Thanks for suggesting a new resource. Please fill out this form and we will get back to you
        asap!
  - type: input
    id: title
    attributes:
      label: Title of the resource
      description: Title of the resource
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Resource type
      options:
        - External resource
        - Hosted resource
        - Pathfinder
        - Captured event
  - type: input
    id: authors
    attributes:
      label: Authors, editors and contributors
      description: Comma-separated list of authors, editors and contributors
    validations:
      required: true
  - type: input
    id: tags
    attributes:
      label: Topics (keywords)
      description:
        Comma-separated list of topics. Please have a look at the [list of existing
        topics](https://campus.dariah.eu/search).
  - type: textarea
    id: learning-outcomes
    attributes:
      label: Learning outcomes
      description: Please add a list of learning outcomes
  - type: textarea
    id: abstract
    attributes:
      label: Abstract
      description: Short description of the resource
    validations:
      required: true
  - type: input
    id: expected-date-of-completion
    attributes:
      label: Expected date of completion
      description: |
        Please provide a realistic date by which you expect to submit your publication-ready resource for editorial review.
        This will allow the Editorial Board to plan and coordinate the process effectively and ensure timely feedback on your submission.
      placeholder: YYYY-MM-DD
    validations:
      required: true
