name: Technical issue
description: Report a technical issue with DARIAH-Campus
assignees:
  - babslgam
labels:
  - needs-review
type: bug
body:
  - type: textarea
    attributes:
      label: Current behavior
      description: A concise description of the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        1. Click on '...'
        1. Scroll down to '...'
        1. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Ubuntu 22.04
          - **Browser**: Firefox
          - **Version**: 136
      value: |
        - OS:
        - Browser:
        - Version:
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Screenshots? Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
