name: Technical issue
description: Report a technical issue with DARIAH-Campus
assignees:
  - stefanprobst
labels:
  - needs-review
body:
  - type: markdown
    attributes:
      value:
        Please provide details on (i) what you were trying to do, (ii) what you expected to happen,
        and (iii) what happened instead.
  - type: textarea
    id: bug
    attributes:
      label: Bug report
    validations:
      required: true
