import { defineConfig } from "oxlint";

const config = defineConfig({
	categories: {
		correctness: "error",
		perf: "error",
		suspicious: "warn",
	},
	env: {
		builtin: true,
	},
	plugins: ["eslint", "import", "node", "oxc", "promise", "typescript", "unicorn"],
	rules: {
		/**
		 * ================================================================================================================
		 * Correctness.
		 * ================================================================================================================
		 */

		"constructor-super": "off",
		"for-direction": "error",
		"no-async-promise-executor": "error",
		"no-caller": "error",
		"no-class-assign": "off",
		"no-compare-neg-zero": "error",
		"no-cond-assign": "error",
		"no-const-assign": "off",
		"no-constant-binary-expression": "error",
		"no-constant-condition": "error",
		"no-control-regex": "error",
		"no-debugger": "error",
		"no-delete-var": "error",
		"no-dupe-class-members": "off",
		"no-dupe-else-if": "error",
		"no-dupe-keys": "off",
		"no-duplicate-case": "error",
		"no-empty-character-class": "error",
		"no-empty-pattern": "error",
		"no-empty-static-block": "error",
		"no-eval": "error",
		"no-ex-assign": "error",
		"no-extra-boolean-cast": "error",
		"no-func-assign": "off",
		"no-global-assign": "error",
		"no-import-assign": "off",
		"no-invalid-regexp": "error",
		"no-irregular-whitespace": "error",
		"no-iterator": "error",
		"no-loss-of-precision": "error",
		"no-misleading-character-class": "error",
		"no-new-native-nonconstructor": "off",
		"no-nonoctal-decimal-escape": "error",
		"no-obj-calls": "off",
		"no-self-assign": "error",
		"no-setter-return": "off",
		"no-shadow-restricted-names": "error",
		"no-sparse-arrays": "error",
		"no-this-before-super": "off",
		"no-unassigned-vars": "error",
		"no-unsafe-finally": "error",
		"no-unsafe-negation": "off",
		"no-unsafe-optional-chaining": "error",
		"no-unused-expressions": "error",
		"no-unused-labels": "error",
		"no-unused-private-class-members": "error",
		"no-unused-vars": "error",
		"no-useless-backreference": "error",
		"no-useless-catch": "error",
		"no-useless-escape": "error",
		"no-useless-rename": "error",
		"no-with": "off",
		"require-yield": "error",
		"use-isnan": "error",
		"valid-typeof": "error",

		"import/default": "error",
		"import/namespace": "error",

		"oxc/bad-array-method-on-arguments": "error",
		"oxc/bad-char-at-comparison": "error",
		"oxc/bad-comparison-sequence": "error",
		"oxc/bad-match-all-arg": "error",
		"oxc/bad-min-max-func": "error",
		"oxc/bad-object-literal-comparison": "error",
		"oxc/bad-replace-all-arg": "error",
		"oxc/const-comparisons": "error",
		"oxc/double-comparisons": "error",
		"oxc/erasing-op": "error",
		"oxc/missing-throw": "error",
		"oxc/number-arg-out-of-range": "error",
		"oxc/only-used-in-recursion": "error",
		"oxc/uninvoked-array-callback": "error",

		"promise/no-callback-in-promise": "error",
		"promise/no-new-statics": "error",
		"promise/valid-params": "error",

		"typescript/await-thenable": "error",
		"typescript/no-array-delete": "error",
		"typescript/no-base-to-string": "error",
		"typescript/no-duplicate-enum-values": "error",
		"typescript/no-duplicate-type-constituents": "error",
		"typescript/no-extra-non-null-assertion": "error",
		"typescript/no-floating-promises": "error",
		"typescript/no-for-in-array": "error",
		"typescript/no-implied-eval": "error",
		"typescript/no-meaningless-void-operator": "error",
		"typescript/no-misused-new": "error",
		"typescript/no-misused-spread": "error",
		"typescript/no-non-null-asserted-optional-chain": "error",
		"typescript/no-redundant-type-constituents": "error",
		"typescript/no-this-alias": "error",
		"typescript/no-unnecessary-parameter-property-assignment": "error",
		"typescript/no-unsafe-declaration-merging": "error",
		"typescript/no-unsafe-unary-minus": "error",
		"typescript/no-useless-default-assignment": "error",
		"typescript/no-useless-empty-export": "error",
		"typescript/no-wrapper-object-types": "error",
		"typescript/prefer-as-const": "error",
		"typescript/require-array-sort-compare": "error",
		"typescript/restrict-template-expressions": [
			"error",
			{
				allowAny: false,
				allowBoolean: false,
				allowNullish: false,
				allowRegExp: false,
			},
		],
		"typescript/triple-slash-reference": "error",
		"typescript/unbound-method": "error",

		"unicorn/no-await-in-promise-methods": "error",
		"unicorn/no-empty-file": "error",
		"unicorn/no-invalid-fetch-options": "error",
		"unicorn/no-invalid-remove-event-listener": "error",
		"unicorn/no-new-array": "error",
		"unicorn/no-single-promise-in-promise-methods": "error",
		"unicorn/no-thenable": "error",
		"unicorn/no-unnecessary-await": "error",
		"unicorn/no-useless-fallback-in-spread": "error",
		"unicorn/no-useless-length-check": "error",
		"unicorn/no-useless-spread": "error",
		"unicorn/prefer-set-size": "error",
		"unicorn/prefer-string-starts-ends-with": "error",

		/**
		 * ================================================================================================================
		 * Suspicious.
		 * ================================================================================================================
		 */

		"block-scoped-var": "warn",
		"no-confusing-non-null-assertion": "error",
		"no-extend-native": "warn",
		"no-extra-bind": "warn",
		"no-extraneous-class": "warn",
		"no-implied-eval": "off",
		"no-new": "warn",
		"no-shadow": "off",
		"no-unexpected-multiline": "warn",
		"no-unmodified-loop-condition": "warn",
		"no-unneeded-ternary": "warn",
		"no-unnecessary-boolean-literal-compare": "error",
		"no-unnecessary-template-expression": "error",
		"no-unnecessary-type-arguments": "error",
		"no-unnecessary-type-assertion": "error",
		"no-unnecessary-type-constraint": "error",
		"no-unsafe-enum-comparison": "error",
		"no-unsafe-type-assertion": "off",
		"no-useless-concat": "warn",
		"no-useless-constructor": "off",
		"preserve-caught-error": "error",

		"import/no-absolute-path": "warn",
		"import/no-empty-named-blocks": "warn",
		"import/no-named-as-default": "warn",
		"import/no-named-as-default-member": "warn",
		"import/no-self-import": "warn",
		"import/no-unassigned-import": ["warn", { allow: ["**/*.css", "server-only"] }],

		"oxc/approx-constant": "warn",
		"oxc/misrefactored-assign-op": "warn",
		"oxc/no-async-endpoint-handlers": "warn",
		"oxc/no-this-in-exported-function": "warn",

		"promise/always-return": "warn",
		"promise/no-multiple-resolved": "warn",
		"promise/no-promise-in-callback": "warn",

		"typescript/consistent-return": "off",
		"typescript/no-unnecessary-type-conversion": "error",
		"typescript/no-unnecessary-type-parameters": "error",

		"unicorn/consistent-function-scoping": "warn",
		"unicorn/no-accessor-recursion": "warn",
		"unicorn/no-array-fill-with-reference-type": "error",
		"unicorn/no-array-reverse": "warn",
		"unicorn/no-array-sort": "warn",
		"unicorn/no-confusing-array-with": "off",
		"unicorn/no-instanceof-builtins": [
			"error",
			{ exclude: ["ArrayBuffer"], strategy: "strict", useErrorIsError: true },
		],
		"unicorn/prefer-add-event-listener": "warn",
		"unicorn/require-module-specifiers": "error",
		"unicorn/require-post-message-target-origin": "error",

		/**
		 * ================================================================================================================
		 * Perf.
		 * ================================================================================================================
		 */

		"no-await-in-loop": "warn",
		"no-useless-call": "error",

		"oxc/no-accumulating-spread": "error",
		"oxc/no-map-spread": "error",

		"unicorn/prefer-array-find": "error",
		"unicorn/prefer-array-flat-map": "error",
		"unicorn/prefer-set-has": "error",

		/**
		 * ================================================================================================================
		 * Pedantic.
		 * ================================================================================================================
		 */

		"accessor-pairs": "off",
		"array-callback-return": "off",
		eqeqeq: ["error", "smart"],
		"max-classes-per-file": "off",
		"max-depth": "off",
		"max-lines": "off",
		"max-lines-per-function": "off",
		"max-nested-callbacks": "off",
		"no-array-constructor": "warn",
		"no-case-declarations": "error",
		"no-constructor-return": "off",
		"no-else-return": "off",
		"no-fallthrough": "error",
		"no-inline-comments": "off",
		"no-inner-declarations": "off",
		"no-lonely-if": "off",
		"no-loop-func": "off",
		"no-negated-condition": "off",
		"no-new-wrappers": "off",
		"no-object-constructor": "off",
		"no-promise-executor-return": "off",
		"no-prototype-builtins": "error",
		"no-redeclare": "error",
		"no-self-compare": "off",
		"no-throw-literal": "off",
		"no-useless-return": "off",
		"no-warning-comments": "off",
		radix: "off",
		"require-await": "off",
		"sort-vars": "off",
		"symbol-description": "off",

		"import/max-dependencies": "off",

		"typescript/ban-ts-comment": [
			"error",
			{
				"ts-check": false,
				"ts-expect-error": { descriptionFormat: "^ -- .+$" },
				"ts-ignore": true,
				"ts-nocheck": { descriptionFormat: "^ -- .+$" },
			},
		],
		"typescript/ban-types": "error",
		"typescript/no-confusing-void-expression": "error",
		"typescript/no-deprecated": "warn",
		"typescript/no-misused-promises": "error",
		"typescript/no-mixed-enums": "error",
		"typescript/no-unsafe-argument": "error",
		"typescript/no-unsafe-assignment": "error",
		"typescript/no-unsafe-call": "error",
		"typescript/no-unsafe-function-type": "error",
		"typescript/no-unsafe-member-access": "error",
		"typescript/no-unsafe-return": "error",
		"typescript/only-throw-error": ["error", { allowThrowingAny: false, allowThrowingUnknown: false }],
		"typescript/prefer-enum-initializers": "error",
		"typescript/prefer-includes": "error",
		"typescript/prefer-nullish-coalescing": "error",
		"typescript/prefer-promise-reject-errors": "error",
		"typescript/prefer-readonly-parameter-types": "off",
		"typescript/prefer-ts-expect-error": "error",
		"typescript/related-getter-setter-pairs": "error",
		"typescript/require-await": "warn",
		"typescript/restrict-plus-operands": [
			"error",
			{
				allowAny: false,
				allowBoolean: false,
				allowNullish: false,
				allowNumberAndString: false,
				allowRegExp: false,
			},
		],
		"typescript/return-await": ["error", "error-handling-correctness-only"],
		"typescript/strict-boolean-expressions": "warn",
		"typescript/strict-void-return": "error",
		"typescript/switch-exhaustiveness-check": "error",

		"unicorn/consistent-assert": "error",
		"unicorn/consistent-empty-array-spread": "error",
		"unicorn/escape-case": "error",
		"unicorn/explicit-length-check": "error",
		"unicorn/new-for-builtins": "error",
		"unicorn/no-array-callback-reference": "warn",
		"unicorn/no-hex-escape": "error",
		"unicorn/no-immediate-mutation": "warn",
		"unicorn/no-instanceof-array": "error",
		"unicorn/no-lonely-if": "warn",
		"unicorn/no-negation-in-equality-check": "error",
		"unicorn/no-new-buffer": "error",
		"unicorn/no-object-as-default-parameter": "error",
		"unicorn/no-static-only-class": "warn",
		"unicorn/no-this-assignment": "warn",
		"unicorn/no-typeof-undefined": "error",
		"unicorn/no-unnecessary-array-flat-depth": "error",
		"unicorn/no-unnecessary-array-splice-count": "error",
		"unicorn/no-unnecessary-slice-end": "error",
		"unicorn/no-unreadable-iife": "error",
		"unicorn/no-useless-promise-resolve-reject": "error",
		"unicorn/no-useless-switch-case": "error",
		"unicorn/no-useless-undefined": "off",
		"unicorn/prefer-array-flat": "warn",
		"unicorn/prefer-array-some": "warn",
		"unicorn/prefer-at": "warn",
		"unicorn/prefer-blob-reading-methods": "warn",
		"unicorn/prefer-code-point": "warn",
		"unicorn/prefer-date-now": "warn",
		"unicorn/prefer-dom-node-append": "warn",
		"unicorn/prefer-dom-node-dataset": "warn",
		"unicorn/prefer-dom-node-remove": "warn",
		"unicorn/prefer-event-target": "warn",
		"unicorn/prefer-import-meta-properties": "warn",
		"unicorn/prefer-math-min-max": "warn",
		"unicorn/prefer-math-trunc": "warn",
		"unicorn/prefer-native-coercion-functions": "warn",
		"unicorn/prefer-number-coercion": "error",
		"unicorn/prefer-prototype-methods": "error",
		"unicorn/prefer-query-selector": "warn",
		"unicorn/prefer-regexp-test": "warn",
		"unicorn/prefer-single-call": "off",
		"unicorn/prefer-string-replace-all": "warn",
		"unicorn/prefer-string-slice": "warn",
		"unicorn/prefer-top-level-await": "off",
		"unicorn/prefer-type-error": "off",
		"unicorn/require-number-to-fixed-digits-argument": "error",

		/**
		 * ================================================================================================================
		 * Restriction.
		 * ================================================================================================================
		 */

		"class-methods-use-this": "off",
		complexity: "off",
		"default-case": "off",
		"no-alert": "off",
		"no-bitwise": "off",
		"no-console": "warn",
		"no-div-regex": "off",
		"no-empty": ["warn", { allowEmptyCatch: true }],
		"no-empty-function": "warn",
		"no-eq-null": "off",
		"no-param-reassign": "warn",
		"no-plusplus": "off",
		"no-proto": "off",
		"no-regex-spaces": "error",
		"no-restricted-globals": "off",
		"no-restricted-imports": "off",
		"no-sequences": "off",
		"no-undefined": "off",
		"no-use-before-define": ["error", { functions: false }],
		"no-var": "warn",
		"no-void": "off",
		"unicode-bom": "off",

		"import/extensions": "off",
		"import/no-amd": "off",
		"import/no-commonjs": "off",
		"import/no-cycle": "off",
		"import/no-default-export": "error",
		"import/no-dynamic-require": "off",
		"import/no-relative-parent-imports": "off",
		"import/no-webpack-loader-syntax": "off",
		"import/unambiguous": "off",

		"node/no-new-require": "off",
		"node/no-path-concat": "error",
		"node/no-process-env": "error",
		"node/no-top-level-await": "warn",

		"oxc/bad-bitwise-operator": "error",
		"oxc/no-async-await": "off",
		"oxc/no-barrel-file": "warn",
		"oxc/no-const-enum": "error",
		"oxc/no-optional-chaining": "off",
		"oxc/no-rest-spread-properties": "off",

		"promise/catch-or-return": "off",
		"promise/spec-only": "off",

		"typescript/explicit-function-return-type": "off",
		"typescript/explicit-member-accessibility": ["error", { accessibility: "no-public" }],
		"typescript/explicit-module-boundary-types": "error",
		"typescript/no-dynamic-delete": "warn",
		"typescript/no-empty-object-type": ["error", { allowInterfaces: "always" }],
		"typescript/no-explicit-any": "warn",
		"typescript/no-import-type-side-effects": "error",
		"typescript/no-invalid-void-type": "error",
		"typescript/no-namespace": ["error", { allowDeclarations: true }],
		"typescript/no-non-null-asserted-nullish-coalescing": "error",
		"typescript/no-non-null-assertion": "off",
		"typescript/no-require-imports": "error",
		"typescript/no-restricted-types": "off",
		"typescript/no-var-requires": "off",
		"typescript/non-nullable-type-assertion-style": "error",
		"typescript/prefer-literal-enum-member": "error",
		"typescript/promise-function-async": "off",
		"typescript/use-unknown-in-catch-callback-variable": "error",

		"unicorn/import-style": "off",
		"unicorn/no-abusive-eslint-disable": "off",
		"unicorn/no-anonymous-default-export": "off",
		"unicorn/no-array-for-each": "off",
		"unicorn/no-array-reduce": "off",
		"unicorn/no-document-cookie": "off",
		"unicorn/no-length-as-slice-end": "off",
		"unicorn/no-magic-array-flat-depth": "off",
		"unicorn/no-process-exit": "error",
		"unicorn/no-useless-error-capture-stack-trace": "off",
		"unicorn/prefer-modern-math-apis": "error",
		"unicorn/prefer-module": "error",
		"unicorn/prefer-node-protocol": "error",
		"unicorn/prefer-number-properties": "error",

		/**
		 * ================================================================================================================
		 * Style.
		 * ================================================================================================================
		 */

		"arrow-body-style": ["error", "as-needed", { requireReturnForObjectLiteral: true }],
		"capitalized-comments": "off",
		curly: ["error", "all"],
		"default-case-last": "error",
		"default-param-last": "off",
		"func-names": "off",
		"func-style": "off",
		"grouped-accessor-pairs": "off",
		"guard-for-in": "off",
		"id-denylist": "off",
		"id-length": "off",
		"id-match": "off",
		"init-declarations": "off",
		"max-params": "off",
		"max-statements": "off",
		"new-cap": "off",
		"no-continue": "off",
		"no-duplicate-imports": "off",
		"no-extra-label": "off",
		"no-implicit-coercion": "error",
		"no-label-var": "off",
		"no-labels": "off",
		"no-lone-blocks": "off",
		"no-magic-numbers": "off",
		"no-multi-assign": "off",
		"no-multi-str": "off",
		"no-nested-ternary": "off",
		"no-new-func": "off",
		"no-return-assign": "off",
		"no-script-url": "off",
		"no-template-curly-in-string": "off",
		"no-ternary": "off",
		"no-useless-computed-key": "off",
		"object-shorthand": "error",
		"one-var": "off",
		"operator-assignment": "off",
		"prefer-const": "error",
		"prefer-destructuring": "off",
		"prefer-exponentiation-operator": "off",
		"prefer-named-capture-group": "warn",
		"prefer-numeric-literals": "off",
		"prefer-object-has-own": "off",
		"prefer-object-spread": "off",
		"prefer-promise-reject-errors": "off",
		"prefer-rest-params": "error",
		"prefer-spread": "error",
		"prefer-template": "error",
		"sort-imports": ["error", { ignoreDeclarationSort: true }],
		"sort-keys": "off",
		"vars-on-top": "off",
		yoda: "off",

		"import/consistent-type-specifier-style": ["error", "prefer-top-level-if-only-type-imports"],
		"import/exports-last": "off",
		"import/first": "error",
		"import/group-exports": "off",
		"import/newline-after-import": "error",
		"import/no-anonymous-default-export": "error",
		"import/no-duplicates": ["error", { preferInline: true }],
		"import/no-mutable-exports": "off",
		"import/no-named-default": "off",
		"import/no-named-export": "off",
		"import/no-namespace": "off",
		"import/no-nodejs-modules": "off",
		"import/prefer-default-export": "off",

		"node/callback-return": "off",
		"node/exports-style": "off",
		"node/global-require": "off",
		"node/no-exports-assign": "off",
		"node/no-mixed-requires": "off",
		"node/no-sync": "off",

		"promise/avoid-new": "off",
		"promise/no-nesting": "off",
		"promise/no-return-wrap": "off",
		"promise/param-names": "off",
		"promise/prefer-await-to-callbacks": "off",
		"promise/prefer-await-to-then": "off",
		"promise/prefer-catch": "off",

		"typescript/adjacent-overload-signatures": "error",
		"typescript/array-type": ["error", { default: "generic" }],
		"typescript/ban-tslint-comment": "off",
		"typescript/class-literal-property-style": "error",
		"typescript/consistent-generic-constructors": "error",
		"typescript/consistent-indexed-object-style": "error",
		"typescript/consistent-type-assertions": "off",
		"typescript/consistent-type-definitions": "error",
		"typescript/consistent-type-exports": ["error", { fixMixedExportsWithInlineTypeSpecifier: true }],
		"typescript/consistent-type-imports": ["error", { fixStyle: "inline-type-imports" }],
		"typescript/dot-notation": ["warn", { allowIndexSignaturePropertyAccess: true }],
		"typescript/method-signature-style": "error",
		"typescript/no-empty-interface": "off",
		"typescript/no-inferrable-types": "error",
		"typescript/no-unnecessary-qualifier": "error",
		"typescript/parameter-properties": "error",
		"typescript/prefer-find": "error",
		"typescript/prefer-for-of": "warn",
		"typescript/prefer-function-type": "warn",
		"typescript/prefer-readonly": "error",
		"typescript/prefer-reduce-type-parameter": "error",
		"typescript/prefer-regexp-exec": "error",
		"typescript/prefer-return-this-type": "error",
		"typescript/prefer-string-starts-ends-with": "error",
		"typescript/unified-signatures": "error",

		"unicorn/catch-error-name": "error",
		"unicorn/consistent-date-clone": "off",
		"unicorn/consistent-existence-index-check": "off",
		"unicorn/consistent-template-literal-escape": "off",
		"unicorn/empty-brace-spaces": "off",
		"unicorn/error-message": "off",
		"unicorn/explicit-timer-delay": "error",
		"unicorn/filename-case": ["error", { case: "kebabCase" }],
		"unicorn/max-nested-calls": "off",
		"unicorn/no-array-method-this-argument": "off",
		"unicorn/no-await-expression-member": "off",
		"unicorn/no-console-spaces": "off",
		"unicorn/no-nested-ternary": "off",
		"unicorn/no-null": "off",
		"unicorn/no-unreadable-array-destructuring": "off",
		"unicorn/no-useless-collection-argument": "off",
		"unicorn/no-zero-fractions": "off",
		"unicorn/number-literal-case": "off",
		"unicorn/numeric-separators-style": "off",
		"unicorn/prefer-array-index-of": "off",
		"unicorn/prefer-bigint-literals": "off",
		"unicorn/prefer-class-fields": "off",
		"unicorn/prefer-classlist-toggle": "off",
		"unicorn/prefer-default-parameters": "off",
		"unicorn/prefer-dom-node-text-content": "off",
		"unicorn/prefer-export-from": ["error", { checkUsedVariables: false }],
		"unicorn/prefer-global-this": "off",
		"unicorn/prefer-includes": "off",
		"unicorn/prefer-keyboard-event-key": "off",
		"unicorn/prefer-logical-operator-over-ternary": "off",
		"unicorn/prefer-modern-dom-apis": "off",
		"unicorn/prefer-negative-index": "off",
		"unicorn/prefer-object-from-entries": "off",
		"unicorn/prefer-optional-catch-binding": "off",
		"unicorn/prefer-reflect-apply": "off",
		"unicorn/prefer-response-static-json": "off",
		"unicorn/prefer-spread": "off",
		"unicorn/prefer-string-raw": "off",
		"unicorn/prefer-string-trim-start-end": "off",
		"unicorn/prefer-structured-clone": "off",
		"unicorn/prefer-ternary": "off",
		"unicorn/relative-url-style": ["warn", "always"],
		"unicorn/require-array-join-separator": "off",
		"unicorn/require-module-attributes": "off",
		"unicorn/switch-case-braces": "error",
		"unicorn/switch-case-break-position": "error",
		"unicorn/text-encoding-identifier-case": ["error", { withDash: true }],
		"unicorn/throw-new-error": "off",

		/**
		 * ================================================================================================================
		 * Nursery.
		 * ================================================================================================================
		 */

		"getter-return": "off",
		"no-restricted-exports": "off",
		"no-undef": "off",
		"no-unreachable": "off",
		"no-unreachable-loop": "error",
		"no-useless-assignment": "error",

		"import/export": "off",
		"import/named": "off",

		"oxc/branches-sharing-code": "warn",

		"promise/no-return-in-finally": "error",

		"typescript/no-unnecessary-condition": "warn",
		"typescript/prefer-optional-chain": "error",

		"unicorn/no-useless-iterator-to-array": "error",
	},
	overrides: [
		{
			files: ["oxfmt.config.ts", "oxlint.config.ts"],
			rules: {
				"import/no-default-export": "off",
			},
		},
		{
			files: ["env.config.ts"],
			rules: {
				"node/no-process-env": "off",
			},
		},
	],
});

export default config;
