import type { CmsCollection } from 'netlify-cms-core'

import * as validation from '@/cms/utils/validation'

/**
 * Events collection.
 */
export const collection: CmsCollection = {
  name: 'events',
  label: 'Events',
  label_singular: 'Event',
  description: '',
  folder: 'content/events',
  path: '{{slug}}/index',
  format: 'frontmatter',
  extension: 'mdx',
  create: true,
  delete: false,
  slug: '{{slug}}',
  media_folder: 'images',
  public_folder: 'images',
  preview_path: 'resource/events/{{dirname}}',
  editor: { preview: true },
  sortable_fields: ['commit_date', 'date', 'title', 'commit_author'],
  view_groups: [
    {
      label: 'Year',
      field: 'date',
      pattern: '\\d{4}',
    },
  ],
  fields: [
    {
      name: 'title',
      label: 'Title',
      hint: '',
    },
    {
      name: 'shortTitle',
      label: 'Short title',
      hint: '',
      required: false,
    },
    {
      name: 'eventType',
      label: 'Event type',
      hint: 'E.g. Winter School',
      required: false,
    },
    {
      name: 'lang',
      label: 'Language',
      hint: '',
      widget: 'select',
      options: [
        {
          label: 'English',
          value: 'en',
        },
      ],
      default: 'en',
    },
    {
      name: 'date',
      label: 'Date',
      hint: '',
      widget: 'datetime',
      date_format: 'DD/MM/YYYY',
      time_format: false,
      picker_utc: true,
      default: '',
    },
    {
      name: 'tags',
      label: 'Topics',
      hint: '',
      widget: 'relation',
      collection: 'tags',
      multiple: true,
      value_field: '{{slug}}',
      search_fields: ['name'],
      display_fields: ['name'],
    },
    {
      name: 'categories',
      label: 'Sources',
      hint: '',
      // widget: 'relation',
      // collection: 'categories',
      // multiple: true,
      // value_field: '{{slug}}',
      // search_fields: ['name'],
      // display_fields: ['name'],
      widget: 'hidden',
      default: ['events'],
    },
    {
      name: 'logo',
      label: 'Logo',
      hint: '',
      required: false,
      widget: 'image',
    },
    {
      name: 'featuredImage',
      label: 'Featured image',
      hint: '',
      required: false,
      widget: 'image',
    },
    {
      name: 'abstract',
      label: 'Abstract',
      hint: 'Provide one or two sentences to briefly describe the event',
      widget: 'text',
    },
    {
      name: 'authors',
      label: 'Persons responsible for the event',
      hint: '',
      required: false,
      widget: 'relation',
      collection: 'people',
      multiple: true,
      value_field: '{{slug}}',
      search_fields: ['firstName', 'lastName'],
      display_fields: ['{{firstName}} {{lastName}}'],
    },
    {
      name: 'body',
      label: 'Short description',
      hint: '',
      widget: 'markdown',
      editor_components: [],
    },
    {
      name: 'about',
      label: 'About',
      hint: '',
      widget: 'markdown',
      editor_components: ['image'],
    },
    {
      name: 'prep',
      label: 'Preparation notes',
      hint: '',
      required: false,
      widget: 'markdown',
      editor_components: ['image', 'code-block'],
    },
    {
      name: 'type',
      label: 'Content type',
      hint: '',
      // widget: 'relation',
      // collection: 'contentTypes',
      // value_field: '{{slug}}',
      // search_fields: ['name'],
      // display_fields: ['name'],
      widget: 'hidden',
      default: 'event',
    },
    {
      name: 'licence',
      label: 'Licence',
      hint: '',
      widget: 'relation',
      collection: 'licences',
      value_field: '{{slug}}',
      search_fields: ['name'],
      display_fields: ['name'],
      default: 'ccby-4.0',
    },
    {
      name: 'partners',
      label: 'Partner organisations',
      label_singular: 'Partner organisation',
      hint: '',
      required: false,
      widget: 'relation',
      collection: 'organisations',
      multiple: true,
      value_field: '{{slug}}',
      search_fields: ['name'],
      display_fields: ['name'],
    },
    {
      name: 'social',
      label: 'Social',
      hint: '',
      required: false,
      widget: 'object',
      collapsed: true,
      fields: [
        {
          name: 'website',
          label: 'Website',
          hint: '',
          required: false,
          pattern: [validation.isUrl, 'Must be a valid URL'],
        },
        {
          name: 'email',
          label: 'Email',
          hint: '',
          required: false,
          pattern: [validation.isEmailLike, 'Must be a valid Email address'],
        },
        {
          name: 'twitter',
          label: 'Twitter handle',
          hint: '',
          required: false,
        },
        {
          name: 'flickr',
          label: 'Flickr',
          hint: '',
          required: false,
        },
      ],
    },
    {
      name: 'synthesis',
      label: 'Synthesis',
      hint: '',
      required: false,
      widget: 'file',
      media_folder: 'downloads',
      public_folder: 'downloads',
    },
    {
      name: 'sessions',
      label: 'Event sessions',
      label_singular: 'Event session',
      hint: '',
      widget: 'list',
      min: 1,
      fields: [
        {
          name: 'title',
          label: 'Title',
          hint: '',
        },
        // {
        //   name: 'shortTitle',
        //   label: 'Short title',
        //   hint: '',
        //   required: false,
        // },
        {
          name: 'speakers',
          label: 'Speakers',
          hint: '',
          widget: 'relation',
          collection: 'people',
          multiple: true,
          value_field: '{{slug}}',
          search_fields: ['firstName', 'lastName'],
          display_fields: ['{{firstName}} {{lastName}}'],
        },
        {
          name: 'body',
          label: 'Content',
          hint: '',
          widget: 'markdown',
          editor_components: [
            'image',
            'code_block',
            'Video',
            'EventSessionSpeakers',
            'EventSessionDownload',
            'EventSessionLink',
          ],
        },
        {
          name: 'synthesis',
          label: 'Synthesis',
          hint: '',
          required: false,
          widget: 'file',
          media_folder: 'downloads',
          public_folder: 'downloads',
        },
      ],
    },
  ],
}
